apiVersion: v2
name: waggle
description: Umbrella chart for Waggle microservices
version: 0.1.0
type: application

dependencies:
  - name: authservice
    version: 0.1.0
    repository: 'file://charts/authservice'
  - name: mediaservice
    version: 0.1.0
    repository: 'file://charts/mediaservice'
  - name: postservice
    version: 0.1.0
    repository: 'file://charts/postservice'
  - name: userservice
    version: 0.1.0
    repository: 'file://charts/userservice'
  - name: likeservice
    version: 0.1.0
    repository: 'file://charts/likeservice'
  - name: followservice
    version: 0.1.0
    repository: 'file://charts/followservice'
  - name: favoriteservice
    version: 0.1.0
    repository: 'file://charts/favoriteservice'
  - name: commentservice
    version: 0.1.0
    repository: 'file://charts/commentservice'
  - name: web
    version: 0.1.0
    repository: 'file://charts/web'
