namespace: app

global:
  imagePullPolicy: IfNotPresent
  environment: Development

authservice:
  name: authservice
  image: waggle-authservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: authservice.localhost

mediaservice:
  name: mediaservice
  image: waggle-mediaservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: mediaservice.localhost

postservice:
  name: postservice
  image: waggle-postservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: postservice.localhost

userservice:
  name: userservice
  image: waggle-userservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: userservice.localhost

likeservice:
  name: likeservice
  image: waggle-likeservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: likeservice.localhost

followservice:
  name: followservice
  image: waggle-followservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: followservice.localhost

favoriteservice:
  name: favoriteservice
  image: waggle-favoriteservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: favoriteservice.localhost

commentservice:
  name: commentservice
  image: waggle-commentservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: commentservice.localhost

web:
  name: web
  image: waggle-web:latest

  ports:
    http: 3000

  ingress:
    host: web.localhost
