namespace: app

global:
  imagePullPolicy: IfNotPresent
  environment: Development

authservice:
  name: authservice
  image: waggle-authservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: authservice.localhost

userservice:
  name: userservice
  image: waggle-userservice:latest

  ports:
    http: 8080
    grpc: 8081

  ingress:
    host: userservice.localhost

web:
  name: web
  image: waggle-web:latest

  ports:
    http: 3000

  ingress:
    host: web.localhost
