image:
  repository: crowdsecurity/crowdsec
  tag: 'v1.7.4'

service:
  port: 8080

persistence:
  size: 1Gi

collections:
  - crowdsecurity/traefik
  - crowdsecurity/base-http-scenarios
  - crowdsecurity/http-cve
  - crowdsecurity/whitelist-good-actors

profiles:
  sqli:
    enabled: true
    banDuration: 2h
