apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-depl
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ports.http }}
          env:
            - name: AUTH_SERVICE_BASE_URL
              value: "http://authservice-svc.app.svc.cluster.local:8080"
            - name: USERS_SERVICE_BASE_URL
              value: "http://userservice-svc.app.svc.cluster.local:8080"
            - name: MEDIA_SERVICE_BASE_URL
              value: "http://mediaservice-svc.app.svc.cluster.local:8080"
            - name: POST_SERVICE_BASE_URL
              value: "http://postservice-svc.app.svc.cluster.local:8080"
            - name: LIKE_SERVICE_BASE_URL
              value: "http://likeservice-svc.app.svc.cluster.local:8080"
            - name: FOLLOW_SERVICE_BASE_URL
              value: "http://followservice-svc.app.svc.cluster.local:8080"
            - name: FAVORITE_SERVICE_BASE_URL
              value: "http://favoriteservice-svc.app.svc.cluster.local:8080"
            - name: COMMENT_SERVICE_BASE_URL
              value: "http://commentservice-svc.app.svc.cluster.local:8080"