apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:1stzorua/waggle.git
    targetRevision: main
    path: infra/k8s/argocd-apps
    directory:
      recurse: false
      include: '{database,gateway,identity,messaging,monitoring,services}.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
