services:
  authservice:
    build:
      context: ../../
      dockerfile: apps/authservice/AuthService/Dockerfile

  userservice:
    build:
      context: ../../
      dockerfile: apps/userservice/UserService/Dockerfile

  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
