services:
  mediaservice:
    build:
      context: ../../
      dockerfile: apps/mediaservice/MediaService/Dockerfile

  authservice:
    build:
      context: ../../
      dockerfile: apps/authservice/AuthService/Dockerfile

  postservice:
    build:
      context: ../../
      dockerfile: apps/postservice/PostService/Dockerfile

  userservice:
    build:
      context: ../../
      dockerfile: apps/userservice/UserService/Dockerfile

  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
