keycloak:
  image:
    repository: bitnamilegacy/keycloak

  auth:
    adminUser: admin
    adminPassword: admin

  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  ingressRoute:
    enabled: true
    host: keycloak.localhost

  extraEnvVars:
    - name: KC_HOSTNAME
      value: 'keycloak.localhost'
    - name: KC_HOSTNAME_STRICT
      value: 'false'
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: 'false'
    - name: KC_HOSTNAME_STRICT_BACKCHANNEL
      value: 'false'
    - name: KC_PROXY_HEADERS
      value: 'xforwarded'
    - name: KC_HTTP_ENABLED
      value: 'true'
    - name: KC_LOG_LEVEL
      value: 'INFO'

  postgresql:
    enabled: true

    image:
      repository: bitnamilegacy/postgresql

    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  global:
    security:
      allowInsecureImages: true
