apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-depl
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        metrics: "true"
    spec:
      hostAliases:
        - ip: "10.43.187.224"
          hostnames:
            - "keycloak.waggle.local"
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.ports.http }}
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: KEYCLOAK_AUTHORITY
              value: "http://keycloak.waggle.local/realms/test-realm"
            - name: KEYCLOAK_AUDIENCE
              value: "test-client"
            - name: POSTGRES_HOST
              value: "favoriteservice-db.database.svc.cluster.local"
            - name: POSTGRES_DB
              value: "favoriteservice"
            - name: POSTGRES_USER
              value: "waggle"
            - name: POSTGRES_PASSWORD
              value: "waggle"
            - name: RabbitMQ__Host
              value: "messaging-rabbitmq.messaging.svc.cluster.local"
            - name: RabbitMQ__Port
              value: "5672"
            - name: RabbitMQ__Username
              value: "admin"
            - name: RabbitMQ__Password
              value: "admin"
            - name: RabbitMQ__VirtualHost
              value: "/"
            - name: Kestrel__Endpoints__webApi__Url
              value: "http://+:8080"
            - name: Kestrel__Endpoints__Grpc__Url
              value: "http://+:8081"
            - name: Kestrel__Endpoints__Grpc__Protocols
              value: "Http2"
            - name: GrpcPost
              value: "http://postservice-svc.app.svc.cluster.local:8081"