apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-depl
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
            - name: grpc
              containerPort: {{ .Values.grpcPort }}
          env:
            - name: Kestrel__Endpoints__webApi__Url
              value: "http://+:8080"
            - name: Kestrel__Endpoints__Grpc__Url
              value: "http://+:8081"
            - name: GrpcAuth
              value: "http://authservice-svc:8081"