apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-forward
  namespace: gateway
spec:
  forwardAuth:
    address: http://authservice-svc.app.svc.cluster.local:8080/api/auth/validate
    trustForwardHeader: true
    authRequestHeaders:
      - Authorization
      - X-ForwardAuth
    authResponseHeaders:
      - X-User-ID
      - X-User-Username
      - X-User-Email
      - X-User-Name
      - X-User-Roles
