apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-config
  namespace: security
data:
  acquis.yaml: |
    source: file
    filenames:
      - /var/log/traefik/access.log
    labels:
      type: traefik
