apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-config
  namespace: security
data:
  acquis.yaml: |
    source: syslog
    listen_addr: 0.0.0.0
    listen_port: 5140
    protocol: tcp
    labels:
      type: syslog

{{- if .Values.profiles.sqli.enabled }}
  sqli-profile.yaml: |
    name: sqli-ban
    filters:
      - Alert.Scenario == "crowdsecurity/http-sqli-probing"
    decisions:
      - type: ban
        duration: {{ .Values.profiles.sqli.banDuration }}
{{- end }}