apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec
  namespace: security
  labels:
    app: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowdsec
  template:
    metadata:
      labels:
        app: crowdsec
    spec:
      containers:
        - name: crowdsec
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: lapi
              containerPort: {{ .Values.service.port }}
          env:
            - name: COLLECTIONS
              value: "{{ join \" \" .Values.collections }}"
          volumeMounts:
            - name: config
              mountPath: /etc/crowdsec/acquis.yaml
              subPath: acquis.yaml
            - name: data
              mountPath: /var/lib/crowdsec/data
{{- if .Values.profiles.sqli.enabled }}
            - name: profiles
              mountPath: /etc/crowdsec/profiles.d/sqli-profile.yaml
              subPath: sqli-profile.yaml
{{- end }}
      volumes:
        - name: config
          configMap:
            name: crowdsec-config
        - name: data
          persistentVolumeClaim:
            claimName: crowdsec-data
{{- if .Values.profiles.sqli.enabled }}
        - name: profiles
          configMap:
            name: crowdsec-config
{{- end }}
