apiVersion: v1
kind: Service
metadata:
  name: crowdsec-service
  namespace: security
  labels:
    app: crowdsec
spec:
  type: ClusterIP
  selector:
    app: crowdsec
  ports:
    - name: lapi
      port: {{ .Values.service.port }}
      targetPort: lapi
      protocol: TCP
    - name: syslog
      port: 5140
      targetPort: 5140
      protocol: TCP