gateway-traefik:
  traefik:
    replicaCount: 2

    api:
      dashboard: true
      insecure: true

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`dashboard.waggle.local`)
