keycloak:
  keycloak:
    replicaCount: 1

    auth:
      adminUser: admin
      adminPassword: admin

    extraEnvVars:
      - name: KC_HOSTNAME
        value: 'keycloak.waggle.local'
      - name: KC_HOSTNAME_URL
        value: 'https://keycloak.waggle.local'
      - name: KC_HOSTNAME_ADMIN_URL
        value: 'https://keycloak.waggle.local'
      - name: KC_PROXY
        value: 'edge'
      - name: KC_PROXY_HEADERS
        value: 'xforwarded'
      - name: KC_HOSTNAME_STRICT
        value: 'true'
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: 'true'
      - name: KC_LOG_LEVEL
        value: 'DEBUG'

    ingressRoute:
      host: keycloak.waggle.local
