crowdsec:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    size: 1Gi

  metrics:
    enabled: true

crowdsec-traefik-bouncer:
  crowdsec:
    lapiKey: 'VXZrUvj9VTsEymTA4RjpCQdTl6it1dorbkkPfe1rpA4'
    logLevel: debug
    updateIntervalSeconds: 10
    defaultDecisionSeconds: 10
