authservice:
  replicaCount: 1
  image: 1stzorua/waggle-authservice:main-2fd00f8

  ingress:
    host: authservice.waggle.local

mediaservice:
  replicaCount: 1
  image: 1stzorua/waggle-mediaservice:main-2fd00f8

  ingress:
    host: mediaservice.waggle.local

postservice:
  replicaCount: 1
  image: 1stzorua/waggle-postservice:main-2fd00f8

  ingress:
    host: postservice.waggle.local

userservice:
  replicaCount: 1
  image: 1stzorua/waggle-userservice:main-2fd00f8

  ingress:
    host: userservice.waggle.local

likeservice:
  replicaCount: 1
  image: 1stzorua/waggle-likeservice:main-2fd00f8

  ingress:
    host: likeservice.waggle.local

followservice:
  replicaCount: 1
  image: 1stzorua/waggle-followservice:main-2fd00f8

  ingress:
    host: followservice.waggle.local

favoriteservice:
  replicaCount: 1
  image: 1stzorua/waggle-favoriteservice:main-2fd00f8

  ingress:
    host: favoriteservice.waggle.local

commentservice:
  replicaCount: 1
  image: 1stzorua/waggle-commentservice:main-2fd00f8

  ingress:
    host: commentservice.waggle.local

web:
  replicaCount: 1
  image: 1stzorua/waggle-web:main-0db301a

  ingress:
    host: web.waggle.local
