authservice:
  replicaCount: 1
  image: 1stzorua/waggle-authservice:main-5d59993

  ingress:
    host: authservice.waggle.local

mediaservice:
  replicaCount: 1
  image: 1stzorua/waggle-mediaservice:main-5d59993

  ingress:
    host: mediaservice.waggle.local

postservice:
  replicaCount: 1
  image: 1stzorua/waggle-postservice:main-5d59993

  ingress:
    host: postservice.waggle.local

userservice:
  replicaCount: 1
  image: 1stzorua/waggle-userservice:main-5d59993

  ingress:
    host: userservice.waggle.local

web:
  replicaCount: 1
  image: 1stzorua/waggle-web:main-5d59993

  ingress:
    host: web.waggle.local
