crowdsec:
  mode: stream
  lapiHost: security-service.security
  lapiPort: 8080
  lapiKey: ''

  appsec:
    enabled: true
    host: security-appsec-service.security
    port: 7422
    failureBlock: true
    unreachableBlock: false

  logLevel: DEBUG
  updateIntervalSeconds: 10
  defaultDecisionSeconds: 10

traefik:
  namespace: gateway
