apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit.fullname" . }}-custom-parsers
  namespace: {{ .Release.Namespace }}
data:
  custom_parsers.conf: |
    # Add any additional custom parsers here if needed