apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-fluent-bit-parsers
  namespace: monitoring
data:
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
