apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit.fullname" . }}-crowdsec-lua
  namespace: {{ .Release.Namespace }}
data:
  crowdsec.lua: |
    function process(tag, timestamp, record)
        -- Example: add a source field
        record["source"] = "traefik"
        return 1, timestamp, record
    end
