apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec
  namespace: {{ .Values.traefik.namespace }}
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: {{ .Values.crowdsec.mode }}
      crowdsecLapiHost: {{ .Values.crowdsec.lapiHost }}:{{ .Values.crowdsec.lapiPort }}
      crowdsecLapiScheme: http
      crowdsecLapiKey: {{ .Values.crowdsec.lapiKey | quote }}
      {{- if .Values.crowdsec.logLevel }}
      logLevel: {{ .Values.crowdsec.logLevel }}
      {{- end }}
      {{- if .Values.crowdsec.updateIntervalSeconds }}
      updateIntervalSeconds: {{ .Values.crowdsec.updateIntervalSeconds }}
      {{- end }}
      {{- if .Values.crowdsec.defaultDecisionSeconds }}
      defaultDecisionSeconds: {{ .Values.crowdsec.defaultDecisionSeconds }}
      {{- end }}
      {{- if .Values.crowdsec.appsec.enabled }}
      crowdsecAppsecEnabled: true
      crowdsecAppsecHost: {{ .Values.crowdsec.appsec.host }}:{{ .Values.crowdsec.appsec.port }}
      crowdsecAppsecFailureBlock: {{ .Values.crowdsec.appsec.failureBlock }}
      crowdsecAppsecUnreachableBlock: {{ .Values.crowdsec.appsec.unreachableBlock }}
      {{- end }}