{{- if .Values.crowdsec.lapiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-key
  namespace: {{ .Values.traefik.namespace }}
type: Opaque
stringData:
  lapiKey: {{ .Values.crowdsec.lapiKey }}
{{- end }}