keycloak:
  keycloak:
    replicaCount: 2

    auth:
      adminUser: admin
      adminPassword: admin

    extraEnvVars:
      - name: KC_HOSTNAME
        value: 'keycloak.waggle.local'
      - name: KC_HOSTNAME_STRICT
        value: 'true'
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: 'true'

    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 1000m
        memory: 1024Mi

    postgresql:
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 512Mi

      persistence:
        enabled: true
        size: 20Gi
