authservice:
  replicaCount: 3
  image: 1stzorua/waggle-authservice:latest

  ingress:
    host: authservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

userservice:
  replicaCount: 3

  ingress:
    host: userservice.waggle.local
    image: 1stzorua/waggle-userservice:latest

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

web:
  replicaCount: 3

  ingress:
    host: web.waggle.local
    image: 1stzorua/waggle-web:latest

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 80
