authservice:
  replicaCount: 3
  image: 1stzorua/waggle-authservice:latest

  ingress:
    host: authservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

mediaservice:
  replicaCount: 3
  image: 1stzorua/waggle-mediaservice:latest

  ingress:
    host: mediaservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

postservice:
  replicaCount: 3
  image: 1stzorua/waggle-postservice:latest

  ingress:
    host: postservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

userservice:
  replicaCount: 3
  image: 1stzorua/waggle-userservice:latest

  ingress:
    host: userservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

likeservice:
  replicaCount: 3
  image: 1stzorua/waggle-likeservice:latest

  ingress:
    host: likeservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

followservice:
  replicaCount: 3
  image: 1stzorua/waggle-followservice:latest

  ingress:
    host: followservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

favoriteservice:
  replicaCount: 3
  image: 1stzorua/waggle-favoriteservice:latest

  ingress:
    host: favoriteservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

commentservice:
  replicaCount: 3
  image: 1stzorua/waggle-commentservice:latest

  ingress:
    host: commentservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

web:
  replicaCount: 3
  image: 1stzorua/waggle-web:latest

  ingress:
    host: web.waggle.local

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 80
