authservice:
  replicaCount: 3
  image: 1stzorua/waggle-authservice:main-2fd00f8

  ingress:
    host: authservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

mediaservice:
  replicaCount: 3
  image: 1stzorua/waggle-mediaservice:main-2fd00f8

  ingress:
    host: mediaservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

postservice:
  replicaCount: 3
  image: 1stzorua/waggle-postservice:main-2fd00f8

  ingress:
    host: postservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

userservice:
  replicaCount: 3
  image: 1stzorua/waggle-userservice:main-2fd00f8

  ingress:
    host: userservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

likeservice:
  replicaCount: 3
  image: 1stzorua/waggle-likeservice:main-2fd00f8

  ingress:
    host: likeservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

followservice:
  replicaCount: 3
  image: 1stzorua/waggle-followservice:main-2fd00f8

  ingress:
    host: followservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

favoriteservice:
  replicaCount: 3
  image: 1stzorua/waggle-favoriteservice:main-2fd00f8

  ingress:
    host: favoriteservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

commentservice:
  replicaCount: 3
  image: 1stzorua/waggle-commentservice:main-2fd00f8

  ingress:
    host: commentservice.waggle.local

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

web:
  replicaCount: 3
  image: 1stzorua/waggle-web:main-8745e3b


  ingress:
    host: web.waggle.local

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 80
