ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

providers:
  kubernetesCRD: 
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.localhost`)
    entryPoints:
      - web
      - websecure
