traefik:
  api:
    dashboard: true
    insecure: true

  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`dashboard.localhost`)
      entryPoints:
        - web
        - websecure

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  entryPoints:
    websecure:
      forwardedHeaders:
        trustedIPs:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16

  metrics:
    prometheus: {}

  experimental:
    plugins:
      crowdsec-bouncer:
        moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
        version: v1.4.6

  volumes:
    - name: crowdsec-api-key
      secret:
        secretName: crowdsec-lapi-key

  volumeMounts:
    - name: crowdsec-api-key
      mountPath: /etc/traefik/crowdsec
      readOnly: true

  env:
    - name: CROWDSEC_API_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-lapi-key
          key: crowdsec-api-key

  logs:
    access:
      enabled: true
      format: json
